const CONFIG = {
    titleWeb: "Tặng bé Ngân",
    introTitle: 'Lê Nguyễn Hồng Ngân❤️',
    introDesc: 'Chúc bé Ngân có một buổi tối thật tuyệt vời nhaaaa',
    btnIntro: 'Bắt đầu nè :3',
    title: 'Khoa yêu Ngân say đắm luôn ó',
    desc: 'Hông bíc liệu Ngân có yêu Khoa hông nè!',
    btnYes: 'Yêu lắm <33',
    btnNo: 'Khôm, hơm có đâu!',
    title2: 'Thế thì Ngân cùng nắm lấy tay Khoa',
    desc2: 'Mình cùng nhau viết nên cuộc tình thiệt đẹp, thiệt tuyệt vời nha!',
    btnYes2: 'Dạaaaaaaaaaa',
    btnNo2: 'Thui ai mà thèm😠',
    question1: 'Khoa cũng yêu Ngân nhiều nhắm nhắm :3',
    btnReply1: 'Tiếp tục nha =))))',
    question2: 'Theo em thì mùa hạ đẹp nhất là?',
    btnReply2: 'Ấn vào đây để trả lời nè :>',
    reply: 'Yêu thì yêu mà không yêu thì yêu <33333333',
    mess: 'Lêu lêu trả lời sai rồi nhaaaaaa',
    messDesc: 'Mùa hạ đẹp nhất là mùa hạ năm nay đó :3',
    btnAccept: 'Bấm vào đây để biết lí do!',
    messLink: 'https://www.facebook.com/messages/t/100007352986118'
}
